version: "3.8"

services:
  app:
    build: .
    ports:
      - "8004:8004"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - DB_NAME=general
      - DB_SSLMODE=disable
      - JWT_SECRET=fkdsjfklds
      - JWT_EXPIRATION=15
      - PORT=8004
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=general
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
